AWSTemplateFormatVersion: 2010-09-09

Parameters:
  awsAdminRole:
    Type: String
    Default: ${opt:awsAdminRole}
  stage:
    Type: String
    Default: ${opt:stage}
  ecrRepoName:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ecrRepoName
      RepositoryPolicyText:
            Version: "2012-10-17"
            Statement:
              - Sid: CodeBuildAccess
                Effect: Allow
                Principal:
                    AWS: !Sub "${awsAdminRole}"
                Action:
                  - "ecr:*"

Outputs:
  RepositoryName:
    Value: !Ref Repository
  RepositoryHost:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
